name: CI

on:
#   schedule:
#      - cron: '0,30 * * * *'  
  push:

jobs:
  job_1:
    name: Python Crawler
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python environment
      uses: actions/setup-python@v2.2.2 
      
      
    - name: Install Dependence
      run: pip install chinese_calendar
    - name: Run pa.py
      run: python pa.py
    - name: list
      run: ls
    
    - name: Upload to this repo
      run: |
        git config --global user.name "daziran96"
        git config --global user.email "499952297@qq.com"
        git add index.html  record.html record.md && echo A
        git commit -m 'upload pa result' && echo B
        git push -u origin master && echo C
        
    - name: Failure test
      if: failure()
      run: | 
        ls
        echo 55555  

